stages:
- name: run file
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-wordpress
      version: 9.0.3
      name: noordev
      targetNamespace: default
- name: github
  steps:
  - publishCatalogConfig:
      path: Demo
      catalogTemplate: deompush
      version: "1.0"
      gitUrl: https://github.com/adsnest/DEMO.git
      gitBranch: master
      gitAuthor: Adsnest
      gitEmail: info@adsnest.com
    envFrom:
    - sourceName: git
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: git
      sourceKey: PASSWORD
      targetKey: PASSWORD
  when:
    event: {}
timeout: 60
notification: {}
